global using MediatR;
global using Microsoft.AspNetCore.Mvc;
global using CollectibleDiecast.Ordering.API.Application.Commands;
global using CollectibleDiecast.Ordering.API.Application.Models;
global using CollectibleDiecast.Ordering.API.Infrastructure.Services;
global using Microsoft.Extensions.Logging;
global using NSubstitute;
global using CollectibleDiecast.Ordering.UnitTests;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
